name: code_climate_checker

on:
    - push


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                pip install poetry
                make install
            - uses: paambaati/codeclimate-action@v8.0.0
              env:
                CC_TEST_REPORTER_ID: 90bb50e90b2574bb50363c0d5dab83e1a9715ebbbc3da4c8d9b17af8fa7cc6b4
              with:
                coverageCommand: make test-coverage
                debug: true
            - name: Check linter
              run: |
                make lint
                make test
